<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/SN_web_lightmode.png" width="300">
</center>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

In this final project, you will apply your knowledge of data analysis by completing a series of hands-on tasks in this lab notebook. The lab consists of 10 tasks, where you will write and execute code to demonstrate your skills.

While working through the lab, remember to save all your code and outputs, then download the Jupyter Notebook, as you will need to submit the completed notebook for the **Final Project: Submission and Evaluation**.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [ ]:
# This lab requires 'httr' and 'rvest'packages, which are already pre-loaded into this lab environment.
# However, if you are working on your local RStudio, please uncomment the below codes and install the packages.

#install.packages("httr")
#install.packages("rvest")

In [5]:
install.packages("httr")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

In [6]:
library(httr)
library(rvest)

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this 

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [7]:

get_wiki_covid19_page <- function() {
    
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country  
  # Which has two parts: 
    # 1) base URL `https://en.wikipedia.org/w/index.php  
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?
    
  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
  query_params <- list(title = "Template:COVID-19_testing_by_country")
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
  response <- GET(url = wiki_base_url, query = query_params)
  # Use the `return` function to return the response
  return(response)
}

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [8]:
# Call the get_wiki_covid19_page function and print the response
covid_response <- get_wiki_covid19_page()
print(covid_response)

Response [https://en.wikipedia.org/w/index.php?title=Template%3ACOVID-19_testing_by_country]
  Date: 2026-09-21 13:30
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 1 MB
<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-fea...
<head>
<meta charset="UTF-8">
<title>Template:COVID-19 testing by country - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-heade...
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.st...
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return...
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid...
...

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [9]:
library(rvest)
# Get the root html node from the http response in task 1 
root_node <- read_html(covid_response)
root_node

{html_document}
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" lang="en" dir="ltr">
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body class="skin--responsive skin-vector skin-vector-search-vue mediawik ...

Get the tables in the HTML root node using `html_nodes` function.

In [11]:
# Get the table node from the root html node
table_node <- html_nodes(root_node, "table")
table_node

{xml_nodeset (4)}
[1] <table class="box-Update plainlinks ombox ombox-content ambox-Update" rol ...
[2] <table class="wikitable plainrowheaders sortable collapsible autocollapse ...
[3] <table class="plainlinks ombox mbox-small ombox-notice" role="presentatio ...
[4] <table class="wikitable mw-templatedata-doc-params">\n<caption><p class=" ...

Read the specific table from the multiple tables in the `table_node` using the `html_table` function and convert it into dataframe using `as.data.frame`

_Hint:- Please read the `table_node` with index 2(ex:- table_node[2])._

In [26]:
# Read the table node and convert it into a data frame, and print the data frame for review
covid_data_frame <- as.data.frame(html_table(table_node[[2]]))
head(covid_data_frame)

  Country or region   Date[a]     Tested  Units[b] Confirmed(cases)
1 Afghanistan         17 Dec 2020 154,767 samples  49,621
2 Albania             18 Feb 2021 428,654 samples  96,838
3 Algeria             2 Nov 2020  230,553 samples  58,574
4 Andorra             23 Feb 2022 300,307 samples  37,958
5 Angola              2 Feb 2021  399,228 samples  20,981
6 Antigua and Barbuda 6 Mar 2021  15,268  samples  832
  Confirmed /tested,% Tested /population,% Confirmed /population,% Ref.
1 32.1                0.40                 0.13                    [1]
2 22.6                15.0                 3.4                     [2]
3 25.4                0.53                 0.13                    [3][4]
4 12.6                387                  49.0                    [5]
5 5.3                 1.3                  0.067                   [6]
6 5.4                 15.9                 0.86                    [7]

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [14]:
# Print the summary of the data frame
summary(covid_data_frame)

 Country or region    Date[a]             Tested            Units[b]
 Length:173         Length:173         Length:173         Length:173
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
 Confirmed(cases)   Confirmed /tested,% Tested /population,%
 Length:173         Length:173          Length:173
 Class :character   Class :character    Class :character
 Mode  :character   Mode  :character    Mode  :character
 Confirmed /population,%     Ref.
 Length:173              Length:173
 Class :character        Class :character
 Mode  :character        Mode  :character

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`. 

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [16]:
preprocess_covid_data_frame <- function(data_frame) {
    
    shape <- dim(data_frame)

    # Remove the World row
    data_frame<-data_frame[!(data_frame$`Country.or.region`=="World"),]
    # Remove the last row
    data_frame <- data_frame[1:172, ]
    
    # We dont need the Units and Ref columns, so can be removed
    data_frame["Ref."] <- NULL
    data_frame["Units.b."] <- NULL
    
    # Renaming the columns
    names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")
    
    # Convert column data types
    data_frame$country <- as.factor(data_frame$country)
    data_frame$date <- as.factor(data_frame$date)
    data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
    data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))
    data_frame$'confirmed.tested.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.tested.ratio`))
    data_frame$'tested.population.ratio' <- as.numeric(gsub(",","",data_frame$`tested.population.ratio`))
    data_frame$'confirmed.population.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.population.ratio`))
    
    return(data_frame)
}

Call the `preprocess_covid_data_frame` function

In [17]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
covid_data_frame_processed <- preprocess_covid_data_frame(covid_data_frame)

Get the summary of the processed data frame again

In [18]:
# Print the summary of the processed data frame again
summary(covid_data_frame_processed)

 country      date         tested      confirmed   confirmed.tested.ratio
 NA's:172   NA's:172   Min.   : NA   Min.   : NA   Min.   : NA
                       1st Qu.: NA   1st Qu.: NA   1st Qu.: NA
                       Median : NA   Median : NA   Median : NA
                       Mean   :NaN   Mean   :NaN   Mean   :NaN
                       3rd Qu.: NA   3rd Qu.: NA   3rd Qu.: NA
                       Max.   : NA   Max.   : NA   Max.   : NA
                       NA's   :172   NA's   :172   NA's   :172
 tested.population.ratio confirmed.population.ratio      NA
 Min.   : NA             Min.   : NA                Length:172
 1st Qu.: NA             1st Qu.: NA                Class :character
 Median : NA             Median : NA                Mode  :character
 Mean   :NaN             Mean   :NaN
 3rd Qu.: NA             3rd Qu.: NA
 Max.   : NA             Max.   : NA
 NA's   :172             NA's   :172

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [19]:
# Export the data frame to a csv file
write.csv(covid_data_frame_processed, "covid.csv", row.names = FALSE)

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [20]:
# Get working directory
wd <- getwd()
# Get exported 
file_path <- paste(wd, sep="", "/covid.csv")
# File path
print(file_path)
file.exists(file_path)

[1] "/resources/RP0101EN/labs/M5/covid.csv"

[1] TRUE

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [28]:
## Download a sample csv file
covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [29]:
# Read covid_data_frame_csv from the csv file
covid_data_frame_csv <- read.csv("covid.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
# Get the 5th to 10th rows, with two "country" "confirmed" columns
covid_data_frame_csv[5:10, c("country", "confirmed")]

   country             confirmed
5  Angola                20981
6  Antigua and Barbuda     832
7  Argentina           2195722
8  Armenia              177104
9  Australia             29130
10 Austria              488007

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [30]:
# Get the total confirmed cases worldwide
total_confirmed <- sum(covid_data_frame_csv$confirmed, na.rm = TRUE)
# Get the total tested cases worldwide
total_tested <- sum(covid_data_frame_csv$tested, na.rm = TRUE)
# Get the positive ratio (confirmed / tested)
positive_ratio <- total_confirmed / total_tested

print(total_confirmed)
print(total_tested)
print(positive_ratio)

[1] 117313932[1] 1698581244[1] 0.06906584

## TASK 6: Get a country list which reported their testing data 

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [31]:
# Get the `country` column
country_col <- covid_data_frame_csv$country
# Check its class (should be character)
class(country_col)
# Sort the countries AtoZ
countries_atoz <- sort(country_col)
# Sort the countries ZtoA
countries_ztoa <- sort(country_col, decreasing = TRUE)
# Print the sorted ZtoA list
print(countries_ztoa)

[1] "character"

  [1] "Zimbabwe"               "Zambia"                 "Vietnam"
  [4] "Venezuela"              "Uzbekistan"             "Uruguay"
  [7] "United States"          "United Kingdom"         "United Arab Emirates"
 [10] "Ukraine"                "Uganda"                 "Turkey"
 [13] "Tunisia"                "Trinidad and Tobago"    "Togo"
 [16] "Thailand"               "Tanzania"               "Taiwan[m]"
 [19] "Switzerland[l]"         "Sweden"                 "Sudan"
 [22] "Sri Lanka"              "Spain"                  "South Sudan"
 [25] "South Korea"            "South Africa"           "Slovenia"
 [28] "Slovakia"               "Singapore"              "Serbia"
 [31] "Senegal"                "Saudi Arabia"           "San Marino"
 [34] "Saint Vincent"          "Saint Lucia"            "Saint Kitts and Nevis"
 [37] "Rwanda"                 "Russia"                 "Romania"
 [40] "Qatar"                  "Portugal"               "Poland"
 [43] "Philippines"            "Peru"                   "Paraguay"
 [46] "Papua New Guinea"       "Panama"                 "Palestine"
 [49] "Pakistan"               "Oman"                   "Norway"
 [52] "Northern Cyprus[k]"     "North Macedonia"        "North Korea"
 [55] "Nigeria"                "Niger"                  "New Zealand"
 [58] "New Caledonia"          "Netherlands"            "Nepal"
 [61] "Namibia"                "Myanmar"                "Mozambique"
 [64] "Morocco"                "Montenegro"             "Mongolia"
 [67] "Moldova[j]"             "Mexico"                 "Mauritius"
 [70] "Mauritania"             "Malta"                  "Mali"
 [73] "Maldives"               "Malaysia"               "Malawi"
 [76] "Madagascar"             "Luxembourg[i]"          "Lithuania"
 [79] "Libya"                  "Liberia"                "Lesotho"
 [82] "Lebanon"                "Latvia"                 "Laos"
 [85] "Kyrgyzstan"             "Kuwait"                 "Kosovo"
 [88] "Kenya"                  "Kazakhstan"             "Jordan"
 [91] "Japan"                  "Jamaica"                "Ivory Coast"
 [94] "Italy"                  "Israel"                 "Ireland"
 [97] "Iraq"                   "Iran"                   "Indonesia"
[100] "India"                  "Iceland"                "Hungary"
[103] "Honduras"               "Haiti"                  "Guyana"
[106] "Guinea-Bissau"          "Guinea"                 "Guatemala"
[109] "Grenada"                "Greenland"              "Greece"
[112] "Ghana"                  "Germany"                "Georgia[h]"
[115] "Gambia"                 "Gabon"                  "France[f][g]"
[118] "Finland"                "Fiji"                   "Faroe Islands"
[121] "Ethiopia"               "Eswatini"               "Estonia"
[124] "Equatorial Guinea"      "El Salvador"            "Egypt"
[127] "Ecuador"                "DR Congo"               "Dominican Republic"
[130] "Dominica"               "Djibouti"               "Denmark[e]"
[133] "Czechia"                "Cyprus[d]"              "Cuba"
[136] "Croatia"                "Costa Rica"             "Colombia"
[139] "China[c]"               "Chile"                  "Chad"
[142] "Canada"                 "Cameroon"               "Cambodia"
[145] "Burundi"                "Burkina Faso"           "Bulgaria"
[148] "Brunei"                 "Brazil"                 "Botswana"
[151] "Bosnia and Herzegovina" "Bolivia"                "Bhutan"
[154] "Benin"                  "Belize"                 "Belgium"
[157] "Belarus"                "Barbados"               "Bangladesh"
[160] "Bahrain"                "Bahamas"                "Azerbaijan"
[163] "Austria"                "Australia"              "Armenia"
[166] "Argentina"              "Antigua and Barbuda"    "Angola"
[169] "Andorra"                "Algeria"                "Albania"
[172] "Afghanistan"

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [33]:
# Use a regular expression `United.+` to find matches
united_matches <- grep("United.+", covid_data_frame_csv$country, value = TRUE)
# Print the matched country names
print(united_matches)

[1] "United Arab Emirates" "United Kingdom"       "United States"

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [35]:
# Select a subset (should be only one row) of data frame based on a selected country name and columns
country_one <- covid_data_frame_csv[covid_data_frame_csv$country == "United States", 
                                    c("country", "confirmed", "confirmed.population.ratio")]
# Select a subset (should be only one row) of data frame based on a selected country name and columns
country_two <- covid_data_frame_csv[covid_data_frame_csv$country == "India", 
                                    c("country", "confirmed", "confirmed.population.ratio")]

print(country_one)
print(country_two)

          country confirmed confirmed.population.ratio
166 United States  29403102                        8.9   country confirmed confirmed.population.ratio
73   India  11359048                       0.82

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [36]:
# Use if-else statement
if (country_one$confirmed.population.ratio > country_two$confirmed.population.ratio) {
    print(paste(country_one$country, "has a lager ratio of confirmed case to population"))
 } else {
    print(paste(country_two$country, "has a lager ratio of confirmed case to population"))
 }

[1] "United States has a lager ratio of confirmed case to population"

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [37]:
# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
threshold <- 1
low_risk <- covid_data_frame_csv[which(covid_data_frame_csv$confirmed.population.ratio < threshold),
                                c("country", "confirmed.population.ratio")]
print(low_risk)

                  country confirmed.population.ratio
1             Afghanistan                    0.13000
3                 Algeria                    0.13000
5                  Angola                    0.06700
6     Antigua and Barbuda                    0.86000
9               Australia                    0.12000
14             Bangladesh                    0.33000
19                  Benin                    0.05200
20                 Bhutan                    0.12000
25                 Brunei                    0.04300
27           Burkina Faso                    0.05800
28                Burundi                    0.00740
29               Cambodia                    0.00520
30               Cameroon                    0.12000
32                   Chad                    0.02900
34               China[c]                    0.00610
38                   Cuba                    0.54000
42               Djibouti                    0.68000
43               Dominica                    0.22000
45               DR Congo                    0.02900
47                  Egypt                    0.19000
48            El Salvador                    0.96000
49      Equatorial Guinea                    0.49000
52               Ethiopia                    0.14000
54                   Fiji                    0.00660
57                  Gabon                    0.05000
58                 Gambia                    0.21000
61                  Ghana                    0.28000
63              Greenland                    0.05500
64                Grenada                    0.13000
66                 Guinea                    0.13000
67          Guinea-Bissau                    0.18000
69                  Haiti                    0.11000
73                  India                    0.82000
74              Indonesia                    0.53000
80            Ivory Coast                    0.13000
81                Jamaica                    0.96000
82                  Japan                    0.34000
85                  Kenya                    0.23000
89                   Laos                    0.00063
92                Lesotho                    0.52000
93                Liberia                    0.04000
97             Madagascar                    0.07600
98                 Malawi                    0.17000
99               Malaysia                    0.99000
101                  Mali                    0.04100
103            Mauritania                    0.39000
104             Mauritius                    0.03900
107              Mongolia                    0.11800
108            Montenegro                    0.53000
110            Mozambique                    0.19000
111               Myanmar                    0.26000
113                 Nepal                    0.98000
115         New Caledonia                    0.02600
116           New Zealand                    0.04100
117                 Niger                    0.02100
118               Nigeria                    0.07600
119           North Korea                    0.00000
124              Pakistan                    0.27000
127      Papua New Guinea                    0.01100
130           Philippines                    0.59000
136                Rwanda                    0.15000
137 Saint Kitts and Nevis                    0.08200
142               Senegal                    0.22000
148           South Korea                    0.17000
149           South Sudan                    0.06700
151             Sri Lanka                    0.40000
152                 Sudan                    0.05300
155             Taiwan[m]                    0.00400
156              Tanzania                    0.00085
157              Thailand                    0.03800
158                  Togo                    0.08600
159   Trinidad and Tobago                    0.57000
162                Uganda                    0.08700
168            Uzbekistan                    0.04100
169             Venezuela                    0.50000
170               Vietnam                    0.00250
171                Zambia                    0.46000
172              Zimbabwe                    0.24000